name: Release
on:
  workflow_dispatch:
  push:
    tags:
      - "v[0-9]"
  pull_request:
    branches:
      - "master"
defaults:
  run:
    shell: bash
permissions:
  contents: write
env:
  NAME: ${{ github.event.repository.name }}
  VERSION: ${{ github.ref_name }}
jobs:
  create-release:
    name: Create release
    runs-on: ubuntu-latest
    steps:
      - &checkout
        name: Checkout
        uses: actions/checkout@v6
        # - name: GitHub - Create release
        #   env:
        #     GH_TOKEN: ${{ github.token }}
        #   run: gh release create --draft ${VERSION}
  build:
    name: "Build ${{ matrix.target }}: ${{ matrix.os }}"
    runs-on: ${{ matrix.os }}
    needs: create-release
    strategy:
      fail-fast: false
      matrix:
        include:
          - target: x86_64-pc-windows-msvc
            os: windows-latest
          - target: x86_64-unknown-linux-gnu
            os: ubuntu-latest
    steps:
      - *checkout
      - name: Setup - Rust toolchain
        uses: actions-rust-lang/setup-rust-toolchain@2b1f5e9b395427c92ee4e3331786ca3c37afe2d7 # v1.16.0
        with:
          target: ${{ matrix.target }}
      - name: Setup - Cross toolchain
        uses: taiki-e/setup-cross-toolchain-action@d62f33b587e73b0004731caebc7d2d46b18a7567 # v1.39.2
        with:
          target: ${{ matrix.target }}
      - name: Build
        run: cargo build --release
      - name: Output - Paths
        id: paths
        env:
          TARGET: ${{ matrix.target }}
        run: |
          suffix=''
          if [[ "${TARGET}" == *-pc-windows-* ]]; then
            suffix='.exe'
          fi
          src_path="./target/${TARGET}/release/${NAME}${suffix}"
          pkg_name="${NAME}-${TARGET}${suffix}"
          cp "${src_path}" "./${pkg_name}"
          echo "pkg_name=${pkg_name}" >> "${GITHUB_OUTPUT}"
